### PR TITLE
Add Ruby Client example

### PR DESCRIPTION
**Pull request by bobbytables**
This adds a simple Ruby client example to hit the our swapi endpoint for films.

### CODE REVIEW

**Comment by pseudomuto** [comment]
Can we have the Makefile keep these up to date like we did for the server?

**Comment by bobbytables** [comment]
> Can we have the Makefile keep these up to date like we did for the server?

Are you saying to generate the protos?

**Comment by pseudomuto** [comment]
Yeah

**Comment by bobbytables** [comment]
> Yeah

Yeah I can add that. Should we use the Docker version that is proposed here: #18  ?

**Comment by pseudomuto** [comment]
I think so yeah. That would make sure it's all using the same version of protoc. Should I just merge that PR?

**Comment by bobbytables** [comment]
Yeah let's merge that and then I'll rebase this PR to add it.

**Comment by pseudomuto** [comment]
Done!

**Comment by pseudomuto** [comment]
This is the weirdest way to slack ever 😄

**Comment by bobbytables** [comment]
Yeah. Can I add do slack reactions on this thing?

**Comment by bobbytables** [comment]
I did some yak shaving on this PR too. I added IDs as a part of the error. It makes the errors more helpful in the examples in the text I've written so far about interceptors. For example:

```
$ ruby client_example.rb
Code: 5, ErrorClass: 'GRPC::NotFound', Message: 5:species with id 'bunk' not found
```

**Review by pseudomuto — APPROVED** [review]
Good call on the ID field 👍 

I say 🐑 🇮🇹

**Comment by bobbytables** [comment]
Ruby protoc added to makefile.

**Pull request merged**
