### PR TITLE
Setup for Golang

### PR DESCRIPTION
**Pull request by pseudomuto**
Adding [retool](https://github.com/twitchtv/retool) to install dep (and other tools as needed later). The value of using retool over just having people install dep themselves is that we'll all be on the same version.

While this isn't a big deal for `dep` specifically, once we get into using codegen having the same version of protoc-gen-go/grpc will be necessary to avoid slight differences in the generated code on each PR.

I've updated the README with setup instructions as well (i.e. ensure you clone in `$GOPATH` and run `make setup`).

### CODE REVIEW

**Review by carlessistare — APPROVED** [review]
Looks pretty good @pseudomuto 
I am used to use godep. How does retool improves godep?

**Comment by pseudomuto** [comment]
> I am used to use godep. How does retool improves godep?

So, there are two things here. The first, is using [dep](https://golang.github.io/dep/docs/introduction.html) over godep, since it's the "official" package manager for golang. It's rather new but seems the be the way things are trending nowadays.

The second piece is using `retool` to install dep. This solves a couple of issues:

* No need to _pollute_ people's global gopath anymore
* Developers will now have the exact same versions of tools (like dep, mockery, protoc-gen-go, etc.)

Retool works by dropping these into `_tools` and making things available via `retool do [COMMAND]`.

**Comment by pseudomuto** [comment]
Added one more commit that adds links to golang and protoc releases to the README. Also made `make lint` for running that docker command

**Comment by konsumer** [comment]
I feel weird hitting the "Merge pull request" button without more discussion, but it looks great to me. Maybe I should put all the npm-run targets into Makefile?

**Review by konsumer — APPROVED** [review]
Looks good. I think I should put all the npm-run stuff in the makefile, just to keep it all in one place, but also I think the node-stuff has less of a need now that the data & proto are put together. Maybe I should just remove tools/ ?

**Comment by pseudomuto** [comment]
> Maybe I should just remove tools/

Yeah, I think it's safe to remove `tools` now.

**Comment by pseudomuto** [comment]
I'm going to run on the assumption that 2 👍's are good enough to merge

**Comment by konsumer** [comment]
I thought about `tools/` a bit more over the weekend. It might be nice to keep it around, and even implement the same endpoints in js (if possible.) I think it might help make gRPC more accessible to more people, and it's been really helpful to me to quickly get endpoints up and play with stuff.

**Pull request merged**
