### PR TITLE
comments, "Star Friends" name changes, and use `_ids` to make linkage clearer

### PR DESCRIPTION
**Pull request by konsumer**
added comments for join-fields and grpc endpoints

### CODE REVIEW

**Comment by bobbytables** [comment]
This should probably update the DB as well right? Won't changing the field names cause the responses to become empty on them in our current setup?

**Comment by konsumer** [comment]
Yeh, I need to update the tooling, too (if we are going to include that.) This is the initial proposition for name-changes, btu I can add the changes to the data to this PR as well.

**Comment by konsumer** [comment]
JSON data is updated. I think I'm going to just skip the data-acquisition tools, as it's not really needed, and our proto already diverges a bit from the generated proto, so it's still only a rough start.

**Comment by konsumer** [comment]
I double-checked with the validator script, and made sure everything matches, so this PR should be ready for merge, but generated code and probly database go-code will need some updating.

**Comment by konsumer** [comment]
Is everyone sold on using `v1` in the package? I like to use a single interface and only add fields, so it's not really a "version", but more of a living spec, with new fields accounted for, and graceful fallback. 

Aside from that, I have an [outstanding issue](https://github.com/konsumer/grpcnode/issues/2) for the demo-server that makes names with more than one `.` break. It's not a big deal if the demo-server doesn't work, and the original issue really needs to be fixed, but that is where it's at.

**Comment by konsumer** [comment]
I fixed that other issue, and fancied-up the tools, so I will update the node examples.

**Review by carlessistare — APPROVED** [review]

**Comment by bobbytables** [comment]
Looks a like a conflict is happening on a file.

**Comment by konsumer** [comment]
Yeh, I think the data & proto changed in both branches. I will try to resolve it.

**Pull request merged**
